AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Solvency Engine for Document Validation (Academic Project)

Resources:
  # DynamoDB table to store final results (APROVED, REJECTED, Ratio).
  SolvencyResultsTable:
    Type: AWS::DynamoDB::Table 
    Properties:
      TableName: SolvencyResultsTable
      AttributeDefinitions:
        - AttributeName: DocumentId
          AttributeType: S 
      KeySchema:
        - AttributeName: DocumentId
          KeyType: HASH 
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      StreamSpecification:
        StreamViewType: NEW_IMAGE 

  # S3 Bucket for original documents
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pv-solvency-documents-2025
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true

  # Initial Lambda function that will trigger the Step Function.
  DocumentTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.12
      CodeUri: src/
      Timeout: 10
      MemorySize: 128
      # Policy to allow writing to the DynamoDB results table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SolvencyResultsTable